### ISSUE TITLE
cifar10-dvs和dvs-gesture的网络模型代码

### ISSUE THREAD

**Issue by mi804** [Ariande1/MS-ResNet#1]
您好，我想复现一下ms-resnet的dvs实验，请问可以提供一下cifar10-dvs和dvs-gesture的网络模型代码吗

**Comment by Ariande1** [comment]
论文中没有进行Gesture的实验，可以参考其他Gestrue的工作并替换对应的残差块结构。
       DVS-CIFAR10所用的结构与CIFAR-10所用的ResNet20是一致的，采用6n+2的层数结构（n为残差块个数，n=3)，与ImageNet结构主要区别在于仅有3个stage并且channel为[16,32,64]，也是在Kaiming ResNet论文中就使用过的结构。
       DVS-CIFAR10的结果是在“Incorporating learnable membrane time constant to enhance learning of spiking neural networks”开源代码基础上替换神经元与网络结构得到的，与其保持了一致的数据处理方法。但这份代码没有保留，还请谅解。
![image](https://github.com/Ariande1/MS-ResNet/assets/69565206/617650c5-096d-4681-82ea-ca2fc0ed9a31)

**Comment by mi804** [comment]
收到！感谢您的回复
