### ISSUE TITLE
Could you please provide the trained models?

### ISSUE THREAD

**Issue by yl5922** [Ariande1/MS-ResNet#2]
Hi, recently I am work on applying SNN to some downstream tasks but it is challenging for me to pretrain ResNets on ImageNet since I have access to limited number of GPUs. Would you please also provide the checkpoints of MR-SNN to facilitate following researches? 

B. R.

**Comment by Ariande1** [comment]
Sure. The pretrained models on ImageNet are available at https://drive.google.com/drive/folders/1NMn6RNMpqi6NqKckgFg0t7ewbct-H6_s?usp=sharing.

**Comment by yl5922** [comment]
Thank you very much!
