### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by Ruichen0424** [Ariande1/MS-ResNet#4]
In MS-Net, the data between the residual blocks are in real form, but in the downsample (shortcut) block of the transition block, the structure used is Conv-bn, in which Conv processes real values ​​instead of spikes. This will slightly destroy the spike-driven characteristics of MS-Net, right? Should also be SN-Conv-BN.

**Comment by Ariande1** [comment]
Yes. The downsample blocks with stride-2 do not conform to the spike-based convolution characteristics. It is feasible to replace them with SN-CONV-BN to achieve a more rigorous, fully spike-driven SNN. Also, SN-CONV-BN can be used for the increased channels only and concatenated with the original features.

**Comment by Ruichen0424** [comment]
Got it, thanks for your reply!
