### ISSUE TITLE
你好，可以提供一下用于cifar10-dvs训练的MS-ResNet20网络结构代码吗

### ISSUE THREAD

**Issue by sombrer** [Ariande1/MS-ResNet#5]

**Comment by Ariande1** [comment]
可以使用同CIFAR-10类似的网络结构，参考这个：https://github.com/Ariande1/MS-ResNet/issues/3#issuecomment-2172555752
并且对第一个stage额外设置stride=2。

**Comment by sombrer** [comment]
> 可以使用同CIFAR-10类似的网络结构，参考这个：[#3 (comment)](https://github.com/Ariande1/MS-ResNet/issues/3#issuecomment-2172555752) 并且对第一个stage额外设置stride=2。

谢谢您
