### ISSUE TITLE
您好，我用MS-ResNet20在cifar10-dvs上进行实验时没能得到论文中的结果，可以提供一下使用的学习率，epoch等超参数吗

### ISSUE THREAD

**Issue by sombrer** [Ariande1/MS-ResNet#6]

**Comment by Ariande1** [comment]
可以参考这个设置，更长一些的epoch会让结果稍好。
![image](https://github.com/user-attachments/assets/03b7a5d9-a114-4657-b97c-d3c3d6fa4288)

**Comment by sombrer** [comment]
谢谢您，我使用该参数训练100轮后达到了74.8效果，更长epoch应该能达到论文中精度，感谢您的回复
